// frontend/src/components/Mainpage.vue
<template>
  <div class="main-page-container">
    <h1>Welcome to Our Website</h1>
    <p>Join amazing events around your area.</p>
    <div class="btn-group" role="group">
      <button class="btn btn-primary" @click="goToLogin">Login</button>
      <button class="btn btn-success" @click="goToSignup">Sign Up</button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Mainpage',
  methods: {
    goToLogin() {
      // Programmatically navigate to the login page
      this.$router.push('/login');
    },
    goToSignup() {
      // Programmatically navigate to the signup page
      this.$router.push('/signup');
    },
  },
};
</script>

<style scoped>
/* Scoped styles specific to this component */
.main-page-container {
  text-align: center;
  margin-top: 50px;
}

.btn-group {
  margin-top: 20px;
}
</style>

// frontend/src/components/MainPage.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom'; // Assuming you're using react-router for navigation
import './MainPage.css'

const Mainpage = () => {
    const navigate = useNavigate(); // Create a navigate function using useNavigate

    const goToLogin = () => {
      // Programmatically navigate to the login page
      navigate('/login'); // Use navigate to change routes
    };
  
    const goToSignup = () => {
      // Programmatically navigate to the signup page
      navigate('/signup'); // Use navigate to change routes
    };

  return (
    <div className="main-page-container">
      <h1>Welcome to Our Website</h1>
      <p>Join amazing events around your area.</p>
      <div className="btn-group" role="group">
        <button className="btn btn-primary" onClick={goToLogin}>Login</button>
        <button className="btn btn-success" onClick={goToSignup}>Sign Up</button>
      </div>
    </div>
  );
};

export default Mainpage;
